### ISSUE TITLE
Compile.py script not working on Windows

### ISSUE THREAD

**Issue by Phyrik** [Sothatsit/RoyalUrClient#82]
When running the `compile.py` script on Windows the following error is thrown:

```
Detected missing NPM dependencies as ./node_modules is missing, installing them...
 .. npm install
Traceback (most recent call last):
  File "compile.py", line 704, in <module>
    install_dependencies(prefix=" .. ")
  File "compile.py", line 580, in install_dependencies
    assert execute_command("npm", "install", prefix=prefix)
  File "compile.py", line 56, in execute_command
    return execute_piped_commands(command, **kwargs)
  File "compile.py", line 83, in execute_piped_commands
    last_process = subprocess.Popen(command, stdout=pipe_out)
  File "C:\Users\Buchanan\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Buchanan\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Sothatsit** [comment]
This has been added as of [8602969](https://github.com/Sothatsit/RoyalUrClient/commit/86029691ff2dd4add5932f81073403df4973decb), thanks @Phyrik!
